/* The following code was generated by JFlex 1.6.1 */

package vsim.assembler;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>vsim/assembler/syntax/lexer.flex</tt>
 */
public final class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int SBACKSLASH = 4;
  public static final int CHARACTER = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\114\1\23\1\24\1\24\1\24\22\0\1\114\1\0\1\21"+
    "\2\0\1\10\1\15\1\25\1\4\1\5\1\6\1\11\1\2\1\12"+
    "\1\1\1\7\1\107\1\105\1\43\1\106\1\47\2\110\1\111\2\104"+
    "\1\3\1\0\1\13\1\0\1\14\2\0\1\65\1\55\1\70\1\72"+
    "\1\56\1\113\1\60\1\75\1\66\1\71\1\112\1\62\1\74\1\64"+
    "\1\77\1\67\1\57\1\100\1\76\1\63\1\61\1\73\1\102\1\101"+
    "\1\112\1\103\1\0\1\22\1\0\1\17\1\112\1\0\1\32\1\41"+
    "\1\34\1\51\1\27\1\46\1\40\1\44\1\35\1\71\1\112\1\45"+
    "\1\54\1\37\1\31\1\52\1\57\1\30\1\33\1\36\1\61\1\115"+
    "\1\50\1\53\1\42\1\26\1\0\1\16\1\0\1\20\6\0\1\24"+
    "\u1fa2\0\1\24\1\24\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\1\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\14\22\1\23\6\22\1\24\2\22"+
    "\1\23\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\17\0\1\46\1\47\3\22\1\50\1\51"+
    "\7\22\1\52\1\53\1\22\1\54\1\22\1\50\10\22"+
    "\1\55\1\56\1\57\1\60\1\61\3\22\1\50\1\22"+
    "\1\62\1\63\1\22\26\0\1\64\2\22\1\65\1\66"+
    "\1\67\1\70\1\71\2\22\1\72\1\73\2\22\1\74"+
    "\1\75\1\76\2\22\1\77\1\100\1\101\1\102\1\103"+
    "\1\104\1\105\1\106\1\107\1\110\1\111\1\112\1\113"+
    "\1\114\1\115\1\116\1\117\1\120\13\0\1\121\10\0"+
    "\1\22\1\122\1\123\1\124\1\22\1\125\1\126\1\127"+
    "\1\130\1\131\1\132\1\133\1\134\1\135\1\136\1\137"+
    "\1\140\1\141\1\142\1\143\1\144\1\145\1\146\1\147"+
    "\1\150\1\151\1\152\1\153\1\154\1\155\1\156\6\0"+
    "\1\157\1\160\2\0\1\161\1\0\1\162\1\163\1\0"+
    "\1\164\1\165\1\166\1\167\1\22\1\170\2\0\1\171"+
    "\3\0\1\172\1\0\1\173\1\174\1\175\1\0\1\176"+
    "\1\157\1\177\1\200";

  private static int [] zzUnpackAction() {
    int [] result = new int[266];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\116\0\234\0\352\0\u0138\0\u0186\0\u0138\0\u0138"+
    "\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u01d4\0\u01d4\0\u0222"+
    "\0\u0270\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u02be"+
    "\0\u030c\0\u035a\0\u03a8\0\u03f6\0\u0444\0\u0492\0\u04e0\0\u052e"+
    "\0\u057c\0\u05ca\0\u0618\0\u01d4\0\u0666\0\u06b4\0\u0702\0\u0750"+
    "\0\u079e\0\u07ec\0\u083a\0\u0888\0\u08d6\0\u0924\0\u0138\0\u0138"+
    "\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138"+
    "\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u0138\0\u0972"+
    "\0\u09c0\0\u0a0e\0\u0a5c\0\u0aaa\0\u0af8\0\u0b46\0\u0b94\0\u0be2"+
    "\0\u0c30\0\u0c7e\0\u0ccc\0\u0d1a\0\u0d68\0\u0db6\0\u0138\0\u0e04"+
    "\0\u0e52\0\u0ea0\0\u0eee\0\u04e0\0\u0f3c\0\u0f8a\0\u0fd8\0\u1026"+
    "\0\u1074\0\u10c2\0\u1110\0\u115e\0\u04e0\0\u04e0\0\u11ac\0\u04e0"+
    "\0\u11fa\0\u1248\0\u1296\0\u12e4\0\u1332\0\u1380\0\u13ce\0\u141c"+
    "\0\u146a\0\u14b8\0\u04e0\0\u04e0\0\u1506\0\u1554\0\u04e0\0\u15a2"+
    "\0\u15f0\0\u163e\0\u168c\0\u16da\0\u04e0\0\u04e0\0\u1728\0\u1776"+
    "\0\u17c4\0\u1812\0\u1860\0\u18ae\0\u18fc\0\u194a\0\u1998\0\u19e6"+
    "\0\u1a34\0\u1a82\0\u1ad0\0\u1b1e\0\u1b6c\0\u1bba\0\u1c08\0\u1c56"+
    "\0\u1ca4\0\u1cf2\0\u1d40\0\u1d8e\0\u1ddc\0\u0138\0\u1e2a\0\u1e78"+
    "\0\u04e0\0\u1ec6\0\u04e0\0\u1f14\0\u1f62\0\u1fb0\0\u1ffe\0\u204c"+
    "\0\u209a\0\u20e8\0\u2136\0\u2184\0\u21d2\0\u04e0\0\u2220\0\u226e"+
    "\0\u04e0\0\u04e0\0\u04e0\0\u22bc\0\u230a\0\u2358\0\u23a6\0\u23f4"+
    "\0\u2442\0\u04e0\0\u04e0\0\u04e0\0\u2490\0\u24de\0\u252c\0\u257a"+
    "\0\u1776\0\u17c4\0\u25c8\0\u2616\0\u2664\0\u26b2\0\u2700\0\u274e"+
    "\0\u279c\0\u27ea\0\u2838\0\u2886\0\u28d4\0\u0138\0\u2922\0\u2970"+
    "\0\u29be\0\u2a0c\0\u2a5a\0\u2aa8\0\u2af6\0\u2b44\0\u2b92\0\u04e0"+
    "\0\u04e0\0\u04e0\0\u2be0\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0"+
    "\0\u04e0\0\u2c2e\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0"+
    "\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0\0\u04e0"+
    "\0\u04e0\0\u04e0\0\u2c7c\0\u04e0\0\u0138\0\u2cca\0\u2d18\0\u2d66"+
    "\0\u2db4\0\u2e02\0\u2e50\0\u2e9e\0\u0138\0\u2eec\0\u2f3a\0\u0138"+
    "\0\u2f88\0\u0138\0\u0138\0\u2fd6\0\u0138\0\u04e0\0\u04e0\0\u04e0"+
    "\0\u3024\0\u04e0\0\u3072\0\u30c0\0\u0138\0\u310e\0\u315c\0\u31aa"+
    "\0\u0138\0\u31f8\0\u04e0\0\u0138\0\u0138\0\u3246\0\u0138\0\u0138"+
    "\0\u0138\0\u0138";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[266];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\5\2\0\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\37\1\44\1\37\1\45\1\42\1\44\1\37"+
    "\1\46\1\37\1\47\1\50\1\43\1\31\3\37\1\45"+
    "\1\51\1\41\1\52\2\37\1\36\1\53\1\46\1\37"+
    "\1\50\1\37\1\54\1\33\1\55\1\47\2\37\3\44"+
    "\1\56\2\44\2\37\1\57\1\37\21\60\1\61\1\62"+
    "\2\0\71\60\21\63\1\64\1\65\1\66\1\0\1\67"+
    "\10\63\1\70\1\71\1\63\1\72\4\63\1\73\40\63"+
    "\1\74\5\63\1\75\22\60\1\76\2\0\1\77\70\60"+
    "\144\0\1\100\1\0\1\101\1\0\1\102\1\103\1\104"+
    "\1\0\1\105\1\0\1\106\1\107\1\0\1\110\1\111"+
    "\1\112\1\0\1\113\1\114\1\115\1\116\106\0\1\44"+
    "\3\0\1\44\34\0\6\44\17\0\1\117\116\0\1\120"+
    "\127\0\1\37\1\121\64\37\1\0\1\37\26\0\6\37"+
    "\1\122\33\37\1\122\23\37\1\0\1\37\26\0\1\37"+
    "\1\123\2\37\1\124\23\37\1\123\35\37\1\0\1\37"+
    "\26\0\2\37\1\125\47\37\1\125\13\37\1\0\1\37"+
    "\26\0\11\37\1\126\3\37\1\124\3\37\1\124\1\37"+
    "\1\127\7\37\1\130\2\37\1\126\5\37\1\127\12\37"+
    "\5\124\2\37\1\0\1\37\26\0\1\37\1\131\1\132"+
    "\6\37\1\133\1\134\1\135\1\37\1\124\1\136\1\137"+
    "\1\37\1\124\1\140\1\37\1\124\2\37\1\135\1\131"+
    "\1\37\1\134\1\141\1\137\1\37\1\133\10\37\1\136"+
    "\2\37\1\132\1\37\1\140\1\37\1\124\1\142\4\124"+
    "\2\37\1\0\1\37\26\0\4\37\1\143\32\37\1\143"+
    "\26\37\1\0\1\37\26\0\66\37\1\0\1\37\26\0"+
    "\4\37\1\144\10\37\1\124\3\37\1\124\2\37\1\124"+
    "\12\37\1\144\17\37\4\124\3\37\1\0\1\37\26\0"+
    "\1\37\1\145\1\37\1\146\24\37\1\145\20\37\1\146"+
    "\14\37\1\0\1\37\26\0\24\37\1\124\41\37\1\0"+
    "\1\37\26\0\1\37\1\147\7\37\1\150\1\151\4\37"+
    "\1\152\10\37\1\147\1\37\1\151\1\37\1\152\1\37"+
    "\1\150\27\37\1\0\1\37\26\0\4\37\1\153\2\37"+
    "\1\154\3\37\1\155\2\37\1\156\3\37\1\157\4\37"+
    "\1\155\3\37\1\160\3\37\1\153\1\154\6\37\1\156"+
    "\4\37\1\157\11\37\1\0\1\37\26\0\7\37\1\161"+
    "\30\37\1\161\25\37\1\0\1\37\26\0\3\37\1\162"+
    "\11\37\1\163\3\37\1\124\27\37\1\162\4\37\1\124"+
    "\1\163\1\142\3\124\2\37\1\0\1\37\26\0\33\37"+
    "\1\164\11\37\1\165\20\37\1\0\1\165\26\0\4\37"+
    "\1\144\32\37\1\144\26\37\1\0\1\37\26\0\11\37"+
    "\1\126\11\37\1\127\7\37\1\130\2\37\1\126\5\37"+
    "\1\127\21\37\1\0\1\37\26\0\2\37\1\166\1\37"+
    "\1\167\32\37\1\167\12\37\1\166\13\37\1\0\1\37"+
    "\26\0\1\37\1\131\1\132\6\37\1\133\1\134\1\135"+
    "\2\37\1\136\1\137\2\37\1\140\4\37\1\135\1\131"+
    "\1\37\1\134\1\141\1\137\1\37\1\133\10\37\1\136"+
    "\2\37\1\132\1\37\1\140\11\37\1\0\1\37\26\0"+
    "\1\37\1\123\26\37\1\123\35\37\1\0\1\37\41\0"+
    "\1\170\1\0\1\44\3\0\1\44\3\0\1\171\1\0"+
    "\1\170\23\0\1\171\2\0\6\44\33\0\1\172\117\0"+
    "\1\173\117\0\1\174\11\0\1\175\77\0\1\176\6\0"+
    "\1\177\5\0\1\200\102\0\1\201\113\0\1\202\133\0"+
    "\1\203\102\0\1\204\1\205\6\0\1\206\114\0\1\207"+
    "\106\0\1\210\114\0\1\211\125\0\1\212\105\0\1\213"+
    "\116\0\1\214\126\0\1\215\66\0\1\216\127\0\2\37"+
    "\1\217\63\37\1\0\1\37\26\0\4\37\1\220\32\37"+
    "\1\220\26\37\1\0\1\37\26\0\10\37\1\221\15\37"+
    "\1\222\6\37\1\221\10\37\1\222\17\37\1\0\1\37"+
    "\26\0\7\37\1\223\30\37\1\223\25\37\1\0\1\37"+
    "\26\0\23\37\1\224\20\37\1\224\21\37\1\0\1\37"+
    "\26\0\23\37\1\225\20\37\1\225\21\37\1\0\1\37"+
    "\26\0\7\37\1\226\30\37\1\226\25\37\1\0\1\37"+
    "\26\0\31\37\1\227\34\37\1\0\1\37\26\0\4\37"+
    "\1\230\12\37\1\231\14\37\1\231\2\37\1\230\26\37"+
    "\1\0\1\37\26\0\1\37\1\232\26\37\1\232\35\37"+
    "\1\0\1\37\26\0\10\37\1\233\24\37\1\233\30\37"+
    "\1\0\1\37\26\0\10\37\1\234\6\37\1\235\14\37"+
    "\1\235\1\234\30\37\1\0\1\37\26\0\13\37\1\236"+
    "\13\37\1\236\36\37\1\0\1\37\26\0\57\37\1\124"+
    "\1\37\1\124\4\37\1\0\1\37\26\0\17\37\1\237"+
    "\14\37\1\237\31\37\1\0\1\37\26\0\7\37\1\240"+
    "\30\37\1\240\25\37\1\0\1\37\26\0\12\37\1\241"+
    "\17\37\1\241\33\37\1\0\1\37\26\0\10\37\1\242"+
    "\13\37\1\243\10\37\1\242\3\37\1\243\24\37\1\0"+
    "\1\37\26\0\31\37\1\244\34\37\1\0\1\37\26\0"+
    "\1\37\1\245\26\37\1\245\35\37\1\0\1\37\26\0"+
    "\1\37\1\246\6\37\1\247\17\37\1\246\4\37\1\247"+
    "\30\37\1\0\1\37\26\0\1\37\1\250\6\37\1\251"+
    "\17\37\1\250\4\37\1\251\30\37\1\0\1\37\26\0"+
    "\33\37\1\252\32\37\1\0\1\37\26\0\33\37\1\253"+
    "\32\37\1\0\1\37\26\0\7\37\1\254\30\37\1\254"+
    "\25\37\1\0\1\37\26\0\45\37\1\255\20\37\1\0"+
    "\1\255\26\0\2\37\1\256\47\37\1\256\13\37\1\0"+
    "\1\37\26\0\15\37\1\124\3\37\1\124\34\37\6\124"+
    "\2\37\1\0\1\37\26\0\17\37\1\257\14\37\1\257"+
    "\31\37\1\0\1\37\26\0\17\37\1\260\14\37\1\260"+
    "\31\37\1\0\1\37\105\0\1\261\1\0\1\261\35\0"+
    "\1\262\2\0\1\262\1\0\1\262\4\0\1\262\1\0"+
    "\1\262\2\0\2\262\1\0\1\262\3\0\2\262\6\0"+
    "\1\262\2\0\1\262\1\0\1\262\11\0\6\262\1\0"+
    "\1\262\32\0\1\263\136\0\1\264\100\0\1\265\116\0"+
    "\1\266\114\0\1\267\111\0\1\270\116\0\1\271\140\0"+
    "\1\272\114\0\1\273\73\0\1\274\131\0\1\275\103\0"+
    "\1\276\120\0\1\277\121\0\1\300\120\0\1\301\107\0"+
    "\1\302\120\0\1\303\103\0\1\304\123\0\1\305\111\0"+
    "\1\306\111\0\3\37\1\124\62\37\1\0\1\37\26\0"+
    "\17\37\1\307\14\37\1\307\31\37\1\0\1\37\26\0"+
    "\33\37\1\310\32\37\1\0\1\37\26\0\7\37\1\311"+
    "\30\37\1\311\25\37\1\0\1\37\26\0\7\37\1\312"+
    "\30\37\1\312\25\37\1\0\1\37\26\0\24\37\1\313"+
    "\14\37\1\313\24\37\1\0\1\37\26\0\1\314\54\37"+
    "\1\314\10\37\1\0\1\37\26\0\7\37\1\315\30\37"+
    "\1\315\25\37\1\0\1\37\26\0\7\37\1\316\30\37"+
    "\1\316\25\37\1\0\1\37\26\0\1\317\54\37\1\317"+
    "\10\37\1\0\1\37\26\0\1\320\54\37\1\320\10\37"+
    "\1\0\1\37\26\0\1\321\6\37\1\322\23\37\1\323"+
    "\4\37\1\322\14\37\1\321\10\37\1\0\1\37\26\0"+
    "\7\37\1\324\30\37\1\324\25\37\1\0\1\37\26\0"+
    "\17\37\1\325\14\37\1\325\31\37\1\0\1\37\26\0"+
    "\17\37\1\326\14\37\1\326\31\37\1\0\1\37\26\0"+
    "\1\327\54\37\1\327\10\37\1\0\1\37\26\0\1\330"+
    "\54\37\1\330\10\37\1\0\1\37\26\0\1\331\32\37"+
    "\1\332\21\37\1\331\10\37\1\0\1\37\26\0\1\333"+
    "\32\37\1\334\21\37\1\333\10\37\1\0\1\37\26\0"+
    "\1\335\32\37\1\336\21\37\1\335\10\37\1\0\1\37"+
    "\26\0\1\337\32\37\1\340\21\37\1\337\10\37\1\0"+
    "\1\37\26\0\33\37\1\341\32\37\1\0\1\37\26\0"+
    "\7\37\1\342\30\37\1\342\25\37\1\0\1\37\26\0"+
    "\16\37\1\343\30\37\1\343\16\37\1\0\1\37\26\0"+
    "\2\37\1\344\47\37\1\344\13\37\1\0\1\37\31\0"+
    "\1\345\116\0\1\346\120\0\1\347\120\0\1\350\113\0"+
    "\1\351\114\0\1\352\110\0\1\353\141\0\1\354\77\0"+
    "\1\355\120\0\1\356\111\0\1\357\107\0\1\360\124\0"+
    "\1\361\125\0\1\362\107\0\1\363\113\0\1\364\130\0"+
    "\1\363\76\0\1\365\130\0\1\175\76\0\17\37\1\366"+
    "\14\37\1\366\31\37\1\0\1\37\26\0\6\37\1\367"+
    "\33\37\1\367\23\37\1\0\1\37\26\0\33\37\1\370"+
    "\32\37\1\0\1\37\26\0\5\37\1\371\25\37\1\372"+
    "\14\37\1\371\15\37\1\0\1\37\36\0\1\373\114\0"+
    "\1\374\117\0\1\375\113\0\1\376\117\0\1\377\114\0"+
    "\1\362\110\0\1\u0100\131\0\1\u0101\110\0\1\u0102\104\0"+
    "\1\362\115\0\1\363\114\0\33\37\1\u0103\32\37\1\0"+
    "\1\37\32\0\1\u0104\111\0\1\u0105\120\0\1\u0106\124\0"+
    "\1\u0107\114\0\1\u0108\115\0\1\u0109\115\0\1\u010a\56\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[12948];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\1\1\7\11\4\1\6\11\27\1\21\11"+
    "\17\0\1\11\50\1\26\0\1\11\44\1\13\0\1\11"+
    "\10\0\36\1\1\11\6\0\1\1\1\11\2\0\1\11"+
    "\1\0\2\11\1\0\1\11\5\1\2\0\1\11\3\0"+
    "\1\11\1\0\1\1\2\11\1\0\4\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[266];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

  private int prevState;
  private StringBuffer text;

  private java_cup.runtime.Symbol symbol(int type) {
    return this.symbol(type, yytext());
  }

  private java_cup.runtime.Symbol symbol(int type, Object value) {
    return new java_cup.runtime.Symbol(type, -1, yycolumn + 1, value);
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.prevState = YYINITIAL;
  this.text = new StringBuffer(0);
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 240) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {   int state = yystate();
  if (state == STRING || state == SBACKSLASH && this.prevState == STRING) {
    yybegin(YYINITIAL);
    return symbol(Token.ERROR, "(syntax) unterminated string constant");
  } else if (state == CHARACTER || state == SBACKSLASH && this.prevState == CHARACTER) {
    yybegin(YYINITIAL);
    return symbol(Token.ERROR, "(syntax) unterminated char constant");
  }
  return symbol(Token.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return symbol(Token.ERROR, "(syntax) unexpected character: '" + yytext() + "'");
            }
          case 129: break;
          case 2: 
            { return symbol(Token.DOT);
            }
          case 130: break;
          case 3: 
            { return symbol(Token.COMMA);
            }
          case 131: break;
          case 4: 
            { return symbol(Token.COLON);
            }
          case 132: break;
          case 5: 
            { return symbol(Token.LPAREN);
            }
          case 133: break;
          case 6: 
            { return symbol(Token.RPAREN);
            }
          case 134: break;
          case 7: 
            { return symbol(Token.TIMES);
            }
          case 135: break;
          case 8: 
            { return symbol(Token.DIVIDE);
            }
          case 136: break;
          case 9: 
            { return symbol(Token.MOD);
            }
          case 137: break;
          case 10: 
            { return symbol(Token.PLUS);
            }
          case 138: break;
          case 11: 
            { return symbol(Token.MINUS);
            }
          case 139: break;
          case 12: 
            { return symbol(Token.AND);
            }
          case 140: break;
          case 13: 
            { return symbol(Token.OR);
            }
          case 141: break;
          case 14: 
            { return symbol(Token.XOR);
            }
          case 142: break;
          case 15: 
            { return symbol(Token.NEG);
            }
          case 143: break;
          case 16: 
            { this.text.setLength(0);
    yybegin(STRING);
            }
          case 144: break;
          case 17: 
            { this.text.setLength(0);
    yybegin(CHARACTER);
            }
          case 145: break;
          case 18: 
            { return symbol(Token.IDENTIFIER, yytext());
            }
          case 146: break;
          case 19: 
            { try {
      return symbol(Token.NUMBER, Integer.parseInt(yytext()));
    } catch (Exception e) {
      return symbol(Token.ERROR, "(32 bits only) invalid number constant: '" + yytext() + "'");
    }
            }
          case 147: break;
          case 20: 
            { return symbol(Token.I_J);
            }
          case 148: break;
          case 21: 
            { /* do nothing */
            }
          case 149: break;
          case 22: 
            { this.text.append(yytext());
            }
          case 150: break;
          case 23: 
            { yybegin(YYINITIAL);
    return symbol(Token.STRING, this.text.toString());
            }
          case 151: break;
          case 24: 
            { this.prevState = STRING;
    yybegin(SBACKSLASH);
            }
          case 152: break;
          case 25: 
            { this.text.append(yytext());
    yybegin(this.prevState);
            }
          case 153: break;
          case 26: 
            { this.text.append("\"");
    yybegin(this.prevState);
            }
          case 154: break;
          case 27: 
            { this.text.append("\\");
    yybegin(this.prevState);
            }
          case 155: break;
          case 28: 
            { this.text.append("\n");
    yybegin(this.prevState);
            }
          case 156: break;
          case 29: 
            { this.text.append("\'");
    yybegin(this.prevState);
            }
          case 157: break;
          case 30: 
            { this.text.append('\t');
    yybegin(this.prevState);
            }
          case 158: break;
          case 31: 
            { this.text.append('\n');
    yybegin(this.prevState);
            }
          case 159: break;
          case 32: 
            { this.text.append('\b');
    yybegin(this.prevState);
            }
          case 160: break;
          case 33: 
            { this.text.append('\f');
    yybegin(this.prevState);
            }
          case 161: break;
          case 34: 
            { this.text.append('\0');
    yybegin(this.prevState);
            }
          case 162: break;
          case 35: 
            { this.text.append((char)11);
    yybegin(this.prevState);
            }
          case 163: break;
          case 36: 
            { this.prevState = CHARACTER;
    yybegin(SBACKSLASH);
            }
          case 164: break;
          case 37: 
            { yybegin(YYINITIAL);
    String ch = this.text.toString();
    if (ch.length() == 1)
      return symbol(Token.CHARACTER, this.text.toString().charAt(0));
    else
      return symbol(Token.ERROR, "invalid char: '" + ch + "'");
            }
          case 165: break;
          case 38: 
            { return symbol(Token.SLL);
            }
          case 166: break;
          case 39: 
            { return symbol(Token.SRA);
            }
          case 167: break;
          case 40: 
            { return symbol(Token.REGISTER, yytext());
            }
          case 168: break;
          case 41: 
            { return symbol(Token.I_OR);
            }
          case 169: break;
          case 42: 
            { return symbol(Token.I_SB);
            }
          case 170: break;
          case 43: 
            { return symbol(Token.I_SH);
            }
          case 171: break;
          case 44: 
            { return symbol(Token.I_SW);
            }
          case 172: break;
          case 45: 
            { return symbol(Token.I_LA);
            }
          case 173: break;
          case 46: 
            { return symbol(Token.I_LI);
            }
          case 174: break;
          case 47: 
            { return symbol(Token.I_LB);
            }
          case 175: break;
          case 48: 
            { return symbol(Token.I_LH);
            }
          case 176: break;
          case 49: 
            { return symbol(Token.I_LW);
            }
          case 177: break;
          case 50: 
            { return symbol(Token.I_MV);
            }
          case 178: break;
          case 51: 
            { return symbol(Token.I_JR);
            }
          case 179: break;
          case 52: 
            { return symbol(Token.SRL);
            }
          case 180: break;
          case 53: 
            { return symbol(Token.I_RET);
            }
          case 181: break;
          case 54: 
            { return symbol(Token.I_REM);
            }
          case 182: break;
          case 55: 
            { return symbol(Token.I_ORI);
            }
          case 183: break;
          case 56: 
            { return symbol(Token.I_AND);
            }
          case 184: break;
          case 57: 
            { return symbol(Token.I_ADD);
            }
          case 185: break;
          case 58: 
            { return symbol(Token.I_SRA);
            }
          case 186: break;
          case 59: 
            { return symbol(Token.I_SRL);
            }
          case 187: break;
          case 60: 
            { return symbol(Token.I_SLT);
            }
          case 188: break;
          case 61: 
            { return symbol(Token.I_SLL);
            }
          case 189: break;
          case 62: 
            { return symbol(Token.I_SUB);
            }
          case 190: break;
          case 63: 
            { return symbol(Token.I_NEG);
            }
          case 191: break;
          case 64: 
            { return symbol(Token.I_NOT);
            }
          case 192: break;
          case 65: 
            { return symbol(Token.I_NOP);
            }
          case 193: break;
          case 66: 
            { return symbol(Token.I_BEQ);
            }
          case 194: break;
          case 67: 
            { return symbol(Token.I_BNE);
            }
          case 195: break;
          case 68: 
            { return symbol(Token.I_BGE);
            }
          case 196: break;
          case 69: 
            { return symbol(Token.I_BGT);
            }
          case 197: break;
          case 70: 
            { return symbol(Token.I_BLE);
            }
          case 198: break;
          case 71: 
            { return symbol(Token.I_BLT);
            }
          case 199: break;
          case 72: 
            { return symbol(Token.I_LBU);
            }
          case 200: break;
          case 73: 
            { return symbol(Token.I_LHU);
            }
          case 201: break;
          case 74: 
            { return symbol(Token.I_LUI);
            }
          case 202: break;
          case 75: 
            { return symbol(Token.I_DIV);
            }
          case 203: break;
          case 76: 
            { return symbol(Token.I_XOR);
            }
          case 204: break;
          case 77: 
            { return symbol(Token.I_MUL);
            }
          case 205: break;
          case 78: 
            { return symbol(Token.I_JAL);
            }
          case 206: break;
          case 79: 
            { try {
      return symbol(Token.NUMBER, Integer.parseUnsignedInt(yytext().substring(2), 2));
    } catch (Exception e) {
      return symbol(Token.ERROR, "(32 bits only) invalid binary constant: '" + yytext() + "'");
    }
            }
          case 207: break;
          case 80: 
            { try {
      return symbol(Token.NUMBER,   Integer.parseUnsignedInt(yytext().substring(2), 16));
    } catch (Exception e) {
      return symbol(Token.ERROR, "(32 bits only) invalid hexadecimal constant: '" + yytext() + "'");
    }
            }
          case 208: break;
          case 81: 
            { return symbol(Token.D_BSS);
            }
          case 209: break;
          case 82: 
            { return symbol(Token.I_REMU);
            }
          case 210: break;
          case 83: 
            { return symbol(Token.I_ANDI);
            }
          case 211: break;
          case 84: 
            { return symbol(Token.I_ADDI);
            }
          case 212: break;
          case 85: 
            { return symbol(Token.I_SEQZ);
            }
          case 213: break;
          case 86: 
            { return symbol(Token.I_SRAI);
            }
          case 214: break;
          case 87: 
            { return symbol(Token.I_SRLI);
            }
          case 215: break;
          case 88: 
            { return symbol(Token.I_SNEZ);
            }
          case 216: break;
          case 89: 
            { return symbol(Token.I_SGTZ);
            }
          case 217: break;
          case 90: 
            { return symbol(Token.I_SLTZ);
            }
          case 218: break;
          case 91: 
            { return symbol(Token.I_SLTI);
            }
          case 219: break;
          case 92: 
            { return symbol(Token.I_SLTU);
            }
          case 220: break;
          case 93: 
            { return symbol(Token.I_SLLI);
            }
          case 221: break;
          case 94: 
            { return symbol(Token.I_CALL);
            }
          case 222: break;
          case 95: 
            { return symbol(Token.I_TAIL);
            }
          case 223: break;
          case 96: 
            { return symbol(Token.I_BEQZ);
            }
          case 224: break;
          case 97: 
            { return symbol(Token.I_BNEZ);
            }
          case 225: break;
          case 98: 
            { return symbol(Token.I_BGEZ);
            }
          case 226: break;
          case 99: 
            { return symbol(Token.I_BGEU);
            }
          case 227: break;
          case 100: 
            { return symbol(Token.I_BGTZ);
            }
          case 228: break;
          case 101: 
            { return symbol(Token.I_BGTU);
            }
          case 229: break;
          case 102: 
            { return symbol(Token.I_BLEZ);
            }
          case 230: break;
          case 103: 
            { return symbol(Token.I_BLEU);
            }
          case 231: break;
          case 104: 
            { return symbol(Token.I_BLTZ);
            }
          case 232: break;
          case 105: 
            { return symbol(Token.I_BLTU);
            }
          case 233: break;
          case 106: 
            { return symbol(Token.I_DIVU);
            }
          case 234: break;
          case 107: 
            { return symbol(Token.I_XORI);
            }
          case 235: break;
          case 108: 
            { return symbol(Token.I_MULH);
            }
          case 236: break;
          case 109: 
            { return symbol(Token.I_JALR);
            }
          case 237: break;
          case 110: 
            { return symbol(Token.D_ZERO);
            }
          case 238: break;
          case 111: 
            { return symbol(Token.D_COMM);
            }
          case 239: break;
          case 112: 
            { return symbol(Token.D_TEXT);
            }
          case 240: break;
          case 113: 
            { return symbol(Token.D_BYTE);
            }
          case 241: break;
          case 114: 
            { return symbol(Token.D_HALF);
            }
          case 242: break;
          case 115: 
            { return symbol(Token.D_WORD);
            }
          case 243: break;
          case 116: 
            { return symbol(Token.D_DATA);
            }
          case 244: break;
          case 117: 
            { return symbol(Token.I_ECALL);
            }
          case 245: break;
          case 118: 
            { return symbol(Token.I_AUIPC);
            }
          case 246: break;
          case 119: 
            { return symbol(Token.I_SLTIU);
            }
          case 247: break;
          case 120: 
            { return symbol(Token.I_MULHU);
            }
          case 248: break;
          case 121: 
            { return symbol(Token.D_ALIGN);
            }
          case 249: break;
          case 122: 
            { return symbol(Token.D_GLOBL);
            }
          case 250: break;
          case 123: 
            { return symbol(Token.I_MULHSU);
            }
          case 251: break;
          case 124: 
            { return symbol(Token.D_RODATA);
            }
          case 252: break;
          case 125: 
            { return symbol(Token.D_ASCIIZ);
            }
          case 253: break;
          case 126: 
            { return symbol(Token.D_STRING);
            }
          case 254: break;
          case 127: 
            { return symbol(Token.D_BALIGN);
            }
          case 255: break;
          case 128: 
            { return symbol(Token.D_SECTION);
            }
          case 256: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
