
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package vsim.assembler;

/** CUP generated class containing symbol constants. */
public class Token {
  /* terminals */
  public static final int I_NOT = 71;
  public static final int IDENTIFIER = 96;
  public static final int TIMES = 7;
  public static final int I_BEQ = 21;
  public static final int I_NOP = 68;
  public static final int I_BNEZ = 78;
  public static final int I_MULH = 39;
  public static final int I_SH = 31;
  public static final int D_TEXT = 104;
  public static final int I_SRAI = 64;
  public static final int I_SB = 30;
  public static final int I_BLEZ = 79;
  public static final int I_MUL = 40;
  public static final int I_SLTZ = 75;
  public static final int I_LW = 59;
  public static final int I_BLEU = 86;
  public static final int I_AUIPC = 28;
  public static final int D_COMM = 111;
  public static final int REGISTER = 95;
  public static final int I_SLTU = 44;
  public static final int I_LUI = 27;
  public static final int D_SECTION = 103;
  public static final int I_LBU = 56;
  public static final int COMMA = 3;
  public static final int D_ALIGN = 108;
  public static final int RPAREN = 6;
  public static final int I_LHU = 58;
  public static final int I_LI = 69;
  public static final int I_SLTIU = 63;
  public static final int I_SLTI = 62;
  public static final int I_LH = 57;
  public static final int D_ZERO = 99;
  public static final int I_LB = 55;
  public static final int I_LA = 67;
  public static final int LPAREN = 5;
  public static final int I_BGEZ = 80;
  public static final int I_ANDI = 52;
  public static final int I_SGTZ = 76;
  public static final int I_ADD = 33;
  public static final int I_DIV = 36;
  public static final int I_BGEU = 23;
  public static final int ERROR = 112;
  public static final int I_SRLI = 65;
  public static final int I_SLT = 46;
  public static final int I_TAIL = 91;
  public static final int I_BEQZ = 77;
  public static final int I_SLL = 45;
  public static final int CHARACTER = 94;
  public static final int MOD = 9;
  public static final int I_SRL = 48;
  public static final int D_ASCIIZ = 98;
  public static final int I_CALL = 90;
  public static final int NUMBER = 92;
  public static final int I_JAL = 29;
  public static final int UPLUS = 20;
  public static final int D_RODATA = 106;
  public static final int I_SRA = 47;
  public static final int PLUS = 10;
  public static final int I_REMU = 42;
  public static final int DIVIDE = 8;
  public static final int I_JR = 88;
  public static final int I_SNEZ = 74;
  public static final int I_RET = 89;
  public static final int I_SLLI = 61;
  public static final int I_DIVU = 35;
  public static final int D_DATA = 105;
  public static final int I_REM = 43;
  public static final int I_ORI = 60;
  public static final int I_JALR = 54;
  public static final int I_XORI = 66;
  public static final int I_ADDI = 51;
  public static final int D_BALIGN = 109;
  public static final int DOT = 2;
  public static final int I_BNE = 26;
  public static final int EOF = 0;
  public static final int SLL = 12;
  public static final int I_AND = 34;
  public static final int I_OR = 41;
  public static final int I_BLTZ = 81;
  public static final int SRL = 13;
  public static final int D_BSS = 107;
  public static final int I_BGT = 83;
  public static final int D_GLOBL = 110;
  public static final int I_NEG = 72;
  public static final int I_BLTU = 25;
  public static final int D_BYTE = 100;
  public static final int I_XOR = 50;
  public static final int MINUS = 11;
  public static final int D_STRING = 97;
  public static final int SRA = 14;
  public static final int OR = 16;
  public static final int error = 1;
  public static final int I_ECALL = 53;
  public static final int I_BGE = 22;
  public static final int COLON = 4;
  public static final int I_SEQZ = 73;
  public static final int I_BGTZ = 82;
  public static final int I_BGTU = 85;
  public static final int I_BLT = 24;
  public static final int I_J = 87;
  public static final int D_WORD = 102;
  public static final int STRING = 93;
  public static final int D_HALF = 101;
  public static final int AND = 15;
  public static final int I_MULHSU = 37;
  public static final int UMINUS = 19;
  public static final int I_BLE = 84;
  public static final int I_SUB = 49;
  public static final int I_MV = 70;
  public static final int NEG = 18;
  public static final int XOR = 17;
  public static final int I_MULHU = 38;
  public static final int I_SW = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOT",
  "COMMA",
  "COLON",
  "LPAREN",
  "RPAREN",
  "TIMES",
  "DIVIDE",
  "MOD",
  "PLUS",
  "MINUS",
  "SLL",
  "SRL",
  "SRA",
  "AND",
  "OR",
  "XOR",
  "NEG",
  "UMINUS",
  "UPLUS",
  "I_BEQ",
  "I_BGE",
  "I_BGEU",
  "I_BLT",
  "I_BLTU",
  "I_BNE",
  "I_LUI",
  "I_AUIPC",
  "I_JAL",
  "I_SB",
  "I_SH",
  "I_SW",
  "I_ADD",
  "I_AND",
  "I_DIVU",
  "I_DIV",
  "I_MULHSU",
  "I_MULHU",
  "I_MULH",
  "I_MUL",
  "I_OR",
  "I_REMU",
  "I_REM",
  "I_SLTU",
  "I_SLL",
  "I_SLT",
  "I_SRA",
  "I_SRL",
  "I_SUB",
  "I_XOR",
  "I_ADDI",
  "I_ANDI",
  "I_ECALL",
  "I_JALR",
  "I_LB",
  "I_LBU",
  "I_LH",
  "I_LHU",
  "I_LW",
  "I_ORI",
  "I_SLLI",
  "I_SLTI",
  "I_SLTIU",
  "I_SRAI",
  "I_SRLI",
  "I_XORI",
  "I_LA",
  "I_NOP",
  "I_LI",
  "I_MV",
  "I_NOT",
  "I_NEG",
  "I_SEQZ",
  "I_SNEZ",
  "I_SLTZ",
  "I_SGTZ",
  "I_BEQZ",
  "I_BNEZ",
  "I_BLEZ",
  "I_BGEZ",
  "I_BLTZ",
  "I_BGTZ",
  "I_BGT",
  "I_BLE",
  "I_BGTU",
  "I_BLEU",
  "I_J",
  "I_JR",
  "I_RET",
  "I_CALL",
  "I_TAIL",
  "NUMBER",
  "STRING",
  "CHARACTER",
  "REGISTER",
  "IDENTIFIER",
  "D_STRING",
  "D_ASCIIZ",
  "D_ZERO",
  "D_BYTE",
  "D_HALF",
  "D_WORD",
  "D_SECTION",
  "D_TEXT",
  "D_DATA",
  "D_RODATA",
  "D_BSS",
  "D_ALIGN",
  "D_BALIGN",
  "D_GLOBL",
  "D_COMM",
  "ERROR"
  };
}

